site_name: My Docs
site_url: https://mydomain.org/mysite
site_description: Blog personale
site_author: Mariasole

# Repository
repo_name: Mariasole03/primo-anno
repo_url: https://github.com/Mariasole03/primo-anno
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - announce.dismiss
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/book-open-page-variant
  favicon: assets/favicon.png

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Mariasole03
      repo: primo-anno
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  # Temporarily comment out the git-revision-date-localized plugin
  # - git-revision-date-localized:
  #     enable_creation_date: true
  # Social plugin removed to avoid Cairo dependency issues

# Extra
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Mariasole03
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourusername
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/yourusername

# Navigation
nav:
  - Home: Lavori/index.md
  - Me: Me.md
  - Lavori:
    - Laboratorio: Lavori/Laboratorio.md
    - NTA: Lavori/installation.md
    - Trama del Territorio: Lavori/configuration.md
  - About: about.md
      
       